# 是否显示进度
print-progress: true

# 并发线程数
concurrent: 50

# 检查间隔(分钟)
check-interval: -1

# 超时时间(毫秒)(节点的最大延迟)
timeout: 3000

# 最低测速结果舍弃(KB/s)
min-speed: 1024

# 下载测试时间(s)
download-timeout: 5

# 👇 必须改成空！GitHub Actions 不能开端口，一开就报错！
listen-port: ""

# 以节点IP查询位置重命名节点
rename-node: false

# 保留之前测试成功的节点
keep-success-proxies: false

# 输出目录（留空自动输出到 output 文件夹）
output-dir: ""

# 通知相关（不用就清空）
apprise-api-server: ""
recipient-url: []

# mihomo 不用就清空
mihomo-api-url: ""
mihomo-api-secret: ""

# 保存方法：本地文件
save-method: local

# 以下全部清空，不用管
webdav-url: ""
webdav-username: ""
webdav-password: ""
github-gist-id: ""
github-token: ""
github-api-mirror: ""
worker-url: ""
worker-token: ""

# 订阅失败重试次数
sub-urls-retry: 3

# 你的订阅链接（保持你自己的）
sub-urls:
  - https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt
